/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tela;

import Cartao.CartaoAposta;
import Cartao.CartaoSorteio;
import java.awt.Color;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;

/**
 *
 * @author User
 */
public class TelaJogo extends javax.swing.JFrame {

    private CartaoAposta aposta;
    private CartaoSorteio sorteio;
    private int totalSelecionado = 0;

    public TelaJogo() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanelNumeros = new javax.swing.JPanel();
        jTB1 = new javax.swing.JToggleButton();
        jTB2 = new javax.swing.JToggleButton();
        jTB3 = new javax.swing.JToggleButton();
        jTB4 = new javax.swing.JToggleButton();
        jTB5 = new javax.swing.JToggleButton();
        jTB6 = new javax.swing.JToggleButton();
        jTB7 = new javax.swing.JToggleButton();
        jTB8 = new javax.swing.JToggleButton();
        jTB9 = new javax.swing.JToggleButton();
        jTB10 = new javax.swing.JToggleButton();
        jTB11 = new javax.swing.JToggleButton();
        jTB12 = new javax.swing.JToggleButton();
        jTB13 = new javax.swing.JToggleButton();
        jTB14 = new javax.swing.JToggleButton();
        jTB15 = new javax.swing.JToggleButton();
        jTB16 = new javax.swing.JToggleButton();
        jTB17 = new javax.swing.JToggleButton();
        jTB18 = new javax.swing.JToggleButton();
        jTB19 = new javax.swing.JToggleButton();
        jTB20 = new javax.swing.JToggleButton();
        jTB21 = new javax.swing.JToggleButton();
        jTB22 = new javax.swing.JToggleButton();
        jTB23 = new javax.swing.JToggleButton();
        jTB24 = new javax.swing.JToggleButton();
        jTB25 = new javax.swing.JToggleButton();
        jTB26 = new javax.swing.JToggleButton();
        jTB27 = new javax.swing.JToggleButton();
        jTB28 = new javax.swing.JToggleButton();
        jTB29 = new javax.swing.JToggleButton();
        jTB30 = new javax.swing.JToggleButton();
        jTB31 = new javax.swing.JToggleButton();
        jTB32 = new javax.swing.JToggleButton();
        jTB33 = new javax.swing.JToggleButton();
        jTB34 = new javax.swing.JToggleButton();
        jTB35 = new javax.swing.JToggleButton();
        jTB36 = new javax.swing.JToggleButton();
        jTB37 = new javax.swing.JToggleButton();
        jTB38 = new javax.swing.JToggleButton();
        jTB39 = new javax.swing.JToggleButton();
        jTB40 = new javax.swing.JToggleButton();
        jTB41 = new javax.swing.JToggleButton();
        jTB42 = new javax.swing.JToggleButton();
        jTB43 = new javax.swing.JToggleButton();
        jTB44 = new javax.swing.JToggleButton();
        jTB45 = new javax.swing.JToggleButton();
        jTB46 = new javax.swing.JToggleButton();
        jTB47 = new javax.swing.JToggleButton();
        jTB48 = new javax.swing.JToggleButton();
        jTB49 = new javax.swing.JToggleButton();
        jTB50 = new javax.swing.JToggleButton();
        jBVerificarAcertos = new javax.swing.JButton();
        jBJogar = new javax.swing.JButton();
        jSResultado = new javax.swing.JScrollPane();
        jTResultado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("7653 Jogo dos números");

        jPanelNumeros.setBorder(javax.swing.BorderFactory.createTitledBorder("Marque entre 6 e 10 números"));

        jTB1.setText("01");
        jTB1.setActionCommand("1");
        jTB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleciona(evt);
            }
        });

        jTB2.setText("02");
        jTB2.setActionCommand("2");
        jTB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleciona(evt);
            }
        });

        jTB3.setText("03");
        jTB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleciona(evt);
            }
        });

        jTB4.setText("04");
        jTB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleciona(evt);
            }
        });

        jTB5.setText("05");
        jTB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleciona(evt);
            }
        });

        jTB6.setText("06");
        jTB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleciona(evt);
            }
        });

        jTB7.setText("07");
        jTB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleciona(evt);
            }
        });

        jTB8.setText("08");
        jTB8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleciona(evt);
            }
        });

        jTB9.setText("09");
        jTB9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleciona(evt);
            }
        });

        jTB10.setText("10");
        jTB10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleciona(evt);
            }
        });

        jTB11.setText("11");
        jTB11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleciona(evt);
            }
        });

        jTB12.setText("12");
        jTB12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleciona(evt);
            }
        });

        jTB13.setText("13");
        jTB13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleciona(evt);
            }
        });

        jTB14.setText("14");
        jTB14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleciona(evt);
            }
        });

        jTB15.setText("15");
        jTB15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleciona(evt);
            }
        });

        jTB16.setText("16");
        jTB16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleciona(evt);
            }
        });

        jTB17.setText("17");
        jTB17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleciona(evt);
            }
        });

        jTB18.setText("18");
        jTB18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleciona(evt);
            }
        });

        jTB19.setText("19");
        jTB19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleciona(evt);
            }
        });

        jTB20.setText("20");
        jTB20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleciona(evt);
            }
        });

        jTB21.setText("21");
        jTB21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleciona(evt);
            }
        });

        jTB22.setText("22");
        jTB22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleciona(evt);
            }
        });

        jTB23.setText("23");
        jTB23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleciona(evt);
            }
        });

        jTB24.setText("24");
        jTB24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleciona(evt);
            }
        });

        jTB25.setText("25");
        jTB25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleciona(evt);
            }
        });

        jTB26.setText("26");
        jTB26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleciona(evt);
            }
        });

        jTB27.setText("27");
        jTB27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleciona(evt);
            }
        });

        jTB28.setText("28");
        jTB28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleciona(evt);
            }
        });

        jTB29.setText("29");
        jTB29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleciona(evt);
            }
        });

        jTB30.setText("30");
        jTB30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleciona(evt);
            }
        });

        jTB31.setText("31");
        jTB31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleciona(evt);
            }
        });

        jTB32.setText("32");
        jTB32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleciona(evt);
            }
        });

        jTB33.setText("33");
        jTB33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleciona(evt);
            }
        });

        jTB34.setText("34");
        jTB34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleciona(evt);
            }
        });

        jTB35.setText("35");
        jTB35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleciona(evt);
            }
        });

        jTB36.setText("36");
        jTB36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleciona(evt);
            }
        });

        jTB37.setText("37");
        jTB37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleciona(evt);
            }
        });

        jTB38.setText("38");
        jTB38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleciona(evt);
            }
        });

        jTB39.setText("39");
        jTB39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleciona(evt);
            }
        });

        jTB40.setText("40");
        jTB40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleciona(evt);
            }
        });

        jTB41.setText("41");
        jTB41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleciona(evt);
            }
        });

        jTB42.setText("42");
        jTB42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleciona(evt);
            }
        });

        jTB43.setText("43");
        jTB43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleciona(evt);
            }
        });

        jTB44.setText("44");
        jTB44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleciona(evt);
            }
        });

        jTB45.setText("45");
        jTB45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleciona(evt);
            }
        });

        jTB46.setText("46");
        jTB46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleciona(evt);
            }
        });

        jTB47.setText("47");
        jTB47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleciona(evt);
            }
        });

        jTB48.setText("48");
        jTB48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleciona(evt);
            }
        });

        jTB49.setText("49");
        jTB49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleciona(evt);
            }
        });

        jTB50.setText("50");
        jTB50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleciona(evt);
            }
        });

        javax.swing.GroupLayout jPanelNumerosLayout = new javax.swing.GroupLayout(jPanelNumeros);
        jPanelNumeros.setLayout(jPanelNumerosLayout);
        jPanelNumerosLayout.setHorizontalGroup(
            jPanelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNumerosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelNumerosLayout.createSequentialGroup()
                        .addComponent(jTB1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTB2))
                    .addGroup(jPanelNumerosLayout.createSequentialGroup()
                        .addComponent(jTB31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTB32))
                    .addGroup(jPanelNumerosLayout.createSequentialGroup()
                        .addComponent(jTB11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTB12))
                    .addGroup(jPanelNumerosLayout.createSequentialGroup()
                        .addComponent(jTB21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTB22))
                    .addGroup(jPanelNumerosLayout.createSequentialGroup()
                        .addComponent(jTB41)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTB42)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNumerosLayout.createSequentialGroup()
                        .addComponent(jTB23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTB24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelNumerosLayout.createSequentialGroup()
                            .addComponent(jTB3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTB4)
                                .addComponent(jTB14, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addComponent(jTB13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNumerosLayout.createSequentialGroup()
                        .addComponent(jTB33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTB34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNumerosLayout.createSequentialGroup()
                        .addComponent(jTB43)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTB44)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelNumerosLayout.createSequentialGroup()
                        .addComponent(jTB15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTB16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTB17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNumerosLayout.createSequentialGroup()
                        .addComponent(jTB5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTB6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTB7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNumerosLayout.createSequentialGroup()
                        .addGroup(jPanelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelNumerosLayout.createSequentialGroup()
                                .addComponent(jTB25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTB26))
                            .addGroup(jPanelNumerosLayout.createSequentialGroup()
                                .addGroup(jPanelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTB35)
                                    .addComponent(jTB45))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTB46)
                                    .addComponent(jTB36))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTB27)
                                .addComponent(jTB37))
                            .addComponent(jTB47))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNumerosLayout.createSequentialGroup()
                        .addComponent(jTB8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTB9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTB10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNumerosLayout.createSequentialGroup()
                        .addGroup(jPanelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTB18)
                            .addComponent(jTB28)
                            .addComponent(jTB38, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTB48, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelNumerosLayout.createSequentialGroup()
                                .addComponent(jTB29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTB30))
                            .addGroup(jPanelNumerosLayout.createSequentialGroup()
                                .addComponent(jTB19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTB20))
                            .addGroup(jPanelNumerosLayout.createSequentialGroup()
                                .addComponent(jTB39)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTB40))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNumerosLayout.createSequentialGroup()
                                .addComponent(jTB49)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTB50)))))
                .addContainerGap())
        );
        jPanelNumerosLayout.setVerticalGroup(
            jPanelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNumerosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTB2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTB3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTB6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTB7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTB4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTB5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTB8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTB9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTB10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTB1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTB17, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTB18, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTB12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTB11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTB13, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTB16, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTB14, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTB15, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTB19, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTB20, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTB24, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTB29, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTB27, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTB30, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTB28, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTB22, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTB21, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTB23, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTB26, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTB25, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTB34, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTB32, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTB31, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTB33, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTB36, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTB37, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTB39, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTB38, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTB40, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTB35, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTB44, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTB50, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTB48, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTB42, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTB41, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTB43, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTB46, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTB47, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTB49, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTB45, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBVerificarAcertos.setText("Verificar");
        jBVerificarAcertos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVerificarAcertosActionPerformed(evt);
            }
        });

        jBJogar.setText("Jogar novamente");
        jBJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBJogarActionPerformed(evt);
            }
        });

        jTResultado.setColumns(20);
        jTResultado.setRows(5);
        jSResultado.setViewportView(jTResultado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBVerificarAcertos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBJogar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jBVerificarAcertos)
                        .addGap(18, 18, 18)
                        .addComponent(jBJogar))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jBVerificarAcertos.setEnabled(false);
        jBJogar.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void seleciona(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleciona
        JToggleButton botao;
        if (evt.getSource() instanceof JToggleButton) {
            botao = (JToggleButton) evt.getSource();
            if (botao.isSelected()) {
                if (totalSelecionado >= 0 && totalSelecionado < 10) {
                    totalSelecionado++;
                } else if (totalSelecionado == 10) {
                    JOptionPane.showMessageDialog(this, "Selecione no maximo 10");
                    botao.setSelected(false);
                }
            } else {
                totalSelecionado--;
            }
            jBVerificarAcertos.setEnabled(totalSelecionado >= 6 && totalSelecionado <= 10);
        }

    }//GEN-LAST:event_seleciona

    private void jBVerificarAcertosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVerificarAcertosActionPerformed
        aposta = new CartaoAposta(totalSelecionado);
        armazenaAposta();
        sorteio = new CartaoSorteio();
        Arrays.sort(sorteio.getNumeros());
        pintaAcertos(aposta.valoresIguais(sorteio));
        jTResultado.setText("Aposta n° " + aposta.getNumeroAposta() + "\nNúmeros sorteados: " + sorteio.numerosCartao() + "\n"
                + "Valor da Aposta: R$ " + aposta.calculaAporta() + "\nTotal de acertos: " + aposta.totAcertos(sorteio));
        jBVerificarAcertos.setEnabled(false);
        jBJogar.setEnabled(true);
        totalSelecionado = 0;


    }//GEN-LAST:event_jBVerificarAcertosActionPerformed

    private void jBJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBJogarActionPerformed
        jBJogar.setEnabled(false);
        for (int c = 0; c < jPanelNumeros.getComponentCount(); c++) {
            if (jPanelNumeros.getComponent(c) instanceof JToggleButton) {
                JToggleButton botao = (JToggleButton) (jPanelNumeros.getComponent(c));
                if (botao.isSelected()) {
                    botao.setSelected(false);
                    botao.setForeground(Color.black);
                    botao.setBackground(null);
                }
            }
        }
        jTResultado.setText("");
    }//GEN-LAST:event_jBJogarActionPerformed

    private void armazenaAposta() {
        for (int c = 0; c < jPanelNumeros.getComponentCount(); c++) {
            if (jPanelNumeros.getComponent(c) instanceof JToggleButton) {
                JToggleButton botao = (JToggleButton) (jPanelNumeros.getComponent(c));
                if (botao.isSelected()) {
                    int nApostado = Integer.parseInt(botao.getActionCommand());
                    int retApost = aposta.addNumeros(nApostado);
                }
            }
        }
    }

//    private void pintaAcertos(int[] acertos) {
//        for (int c = 0; c < jPanelNumeros.getComponentCount(); c++) {
//            if (jPanelNumeros.getComponent(c) instanceof JToggleButton) {
//                JToggleButton botao = (JToggleButton) (jPanelNumeros.getComponent(c));
//                if (botao.isSelected()) {
//                    if (sorteio.existe(Integer.parseInt(botao.getActionCommand()))) {
//                        botao.setBackground(Color.DARK_GRAY);
//                        botao.setForeground(Color.green);
//                    }
//                }
//            }
//        }
//    }
    private void pintaAcertos(int[] acertos) {
        for (int c = 0; c < jPanelNumeros.getComponentCount(); c++) {
            if (jPanelNumeros.getComponent(c) instanceof JToggleButton) {
                JToggleButton botao = (JToggleButton) (jPanelNumeros.getComponent(c));
                if (botao.isSelected()) {
                    for (int valor : acertos) {
                        if (valor == (Integer.parseInt(botao.getActionCommand()))) {
                            botao.setBackground(Color.DARK_GRAY);
                            botao.setForeground(Color.green);
                        }
                    }
                }
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaJogo().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBJogar;
    private javax.swing.JButton jBVerificarAcertos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelNumeros;
    private javax.swing.JScrollPane jSResultado;
    private javax.swing.JToggleButton jTB1;
    private javax.swing.JToggleButton jTB10;
    private javax.swing.JToggleButton jTB11;
    private javax.swing.JToggleButton jTB12;
    private javax.swing.JToggleButton jTB13;
    private javax.swing.JToggleButton jTB14;
    private javax.swing.JToggleButton jTB15;
    private javax.swing.JToggleButton jTB16;
    private javax.swing.JToggleButton jTB17;
    private javax.swing.JToggleButton jTB18;
    private javax.swing.JToggleButton jTB19;
    private javax.swing.JToggleButton jTB2;
    private javax.swing.JToggleButton jTB20;
    private javax.swing.JToggleButton jTB21;
    private javax.swing.JToggleButton jTB22;
    private javax.swing.JToggleButton jTB23;
    private javax.swing.JToggleButton jTB24;
    private javax.swing.JToggleButton jTB25;
    private javax.swing.JToggleButton jTB26;
    private javax.swing.JToggleButton jTB27;
    private javax.swing.JToggleButton jTB28;
    private javax.swing.JToggleButton jTB29;
    private javax.swing.JToggleButton jTB3;
    private javax.swing.JToggleButton jTB30;
    private javax.swing.JToggleButton jTB31;
    private javax.swing.JToggleButton jTB32;
    private javax.swing.JToggleButton jTB33;
    private javax.swing.JToggleButton jTB34;
    private javax.swing.JToggleButton jTB35;
    private javax.swing.JToggleButton jTB36;
    private javax.swing.JToggleButton jTB37;
    private javax.swing.JToggleButton jTB38;
    private javax.swing.JToggleButton jTB39;
    private javax.swing.JToggleButton jTB4;
    private javax.swing.JToggleButton jTB40;
    private javax.swing.JToggleButton jTB41;
    private javax.swing.JToggleButton jTB42;
    private javax.swing.JToggleButton jTB43;
    private javax.swing.JToggleButton jTB44;
    private javax.swing.JToggleButton jTB45;
    private javax.swing.JToggleButton jTB46;
    private javax.swing.JToggleButton jTB47;
    private javax.swing.JToggleButton jTB48;
    private javax.swing.JToggleButton jTB49;
    private javax.swing.JToggleButton jTB5;
    private javax.swing.JToggleButton jTB50;
    private javax.swing.JToggleButton jTB6;
    private javax.swing.JToggleButton jTB7;
    private javax.swing.JToggleButton jTB8;
    private javax.swing.JToggleButton jTB9;
    private javax.swing.JTextArea jTResultado;
    // End of variables declaration//GEN-END:variables

    private void habilita(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
