package operacoesComDoisNumeros;

import javax.swing.JOptionPane;

public class DoisNumerosInteirosAPP extends javax.swing.JFrame {

    private DoisNumerosInteiros doisNumerosObj;

    public DoisNumerosInteirosAPP() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPValores = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFNumero1 = new javax.swing.JTextField();
        jTFNumero2 = new javax.swing.JTextField();
        jPResultado = new javax.swing.JPanel();
        jLResultado = new javax.swing.JLabel();
        jPOperacoes = new javax.swing.JPanel();
        jBtAdicao = new javax.swing.JButton();
        jBtSubtracao = new javax.swing.JButton();
        jBtMultiplicacao = new javax.swing.JButton();
        jBtLimpar = new javax.swing.JButton();
        jBtSair = new javax.swing.JButton();
        jBtDiv = new javax.swing.JButton();
        jBDivPar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Exemplo de  tratamento de exceção em Java");
        setResizable(false);

        jPValores.setBorder(javax.swing.BorderFactory.createTitledBorder("Valores:"));

        jLabel1.setText("Número:");

        jLabel2.setText("Número:");

        javax.swing.GroupLayout jPValoresLayout = new javax.swing.GroupLayout(jPValores);
        jPValores.setLayout(jPValoresLayout);
        jPValoresLayout.setHorizontalGroup(
            jPValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPValoresLayout.createSequentialGroup()
                .addGroup(jPValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPValoresLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTFNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPValoresLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTFNumero2)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPValoresLayout.setVerticalGroup(
            jPValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPValoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        jPResultado.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado:"));

        javax.swing.GroupLayout jPResultadoLayout = new javax.swing.GroupLayout(jPResultado);
        jPResultado.setLayout(jPResultadoLayout);
        jPResultadoLayout.setHorizontalGroup(
            jPResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPResultadoLayout.setVerticalGroup(
            jPResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPResultadoLayout.createSequentialGroup()
                .addComponent(jLResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPOperacoes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operações:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(102, 0, 0))); // NOI18N

        jBtAdicao.setText("Adição");
        jBtAdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAdicaoActionPerformed(evt);
            }
        });

        jBtSubtracao.setText("Subtração");
        jBtSubtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtSubtracaoActionPerformed(evt);
            }
        });

        jBtMultiplicacao.setText("Multiplicação");
        jBtMultiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtMultiplicacaoActionPerformed(evt);
            }
        });

        jBtLimpar.setText("Limpar");
        jBtLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtLimparActionPerformed(evt);
            }
        });

        jBtSair.setText("Sair");
        jBtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtSairActionPerformed(evt);
            }
        });

        jBtDiv.setText("Divisão");
        jBtDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtDivActionPerformed(evt);
            }
        });

        jBDivPar.setText("Divisão Par");
        jBDivPar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDivParActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPOperacoesLayout = new javax.swing.GroupLayout(jPOperacoes);
        jPOperacoes.setLayout(jPOperacoesLayout);
        jPOperacoesLayout.setHorizontalGroup(
            jPOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOperacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtAdicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtSubtracao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtMultiplicacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtDiv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBDivPar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPOperacoesLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBtAdicao, jBtDiv, jBtLimpar, jBtMultiplicacao, jBtSair, jBtSubtracao});

        jPOperacoesLayout.setVerticalGroup(
            jPOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOperacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtAdicao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtSubtracao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtMultiplicacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtDiv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBDivPar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtSair)
                .addGap(20, 20, 20))
        );

        jPOperacoesLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBtAdicao, jBtDiv, jBtLimpar, jBtMultiplicacao, jBtSair, jBtSubtracao});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPResultado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPValores, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(jPOperacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPOperacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPValores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 49, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtAdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAdicaoActionPerformed
        realizaOperacao('+');
    }//GEN-LAST:event_jBtAdicaoActionPerformed

    private void jBtSubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtSubtracaoActionPerformed
        realizaOperacao('-');
    }//GEN-LAST:event_jBtSubtracaoActionPerformed

    private void jBtMultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtMultiplicacaoActionPerformed
        realizaOperacao('*');
    }//GEN-LAST:event_jBtMultiplicacaoActionPerformed

    private void jBtLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtLimparActionPerformed
        jTFNumero1.setText(null);
        jTFNumero2.setText(null);
        jLResultado.setText("");
        jTFNumero1.requestFocusInWindow();
    }//GEN-LAST:event_jBtLimparActionPerformed

    private void jBtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBtSairActionPerformed

    private void jBtDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtDivActionPerformed
        realizaOperacao('/');
    }//GEN-LAST:event_jBtDivActionPerformed

    private void jBDivParActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDivParActionPerformed
        realizaOperacao('.');
    }//GEN-LAST:event_jBDivParActionPerformed

    private void realizaOperacao(char op) {
        int numero1;
        int numero2;
        try {
            numero1 = Integer.parseInt(jTFNumero1.getText());
        } catch (NumberFormatException erro) {
            JOptionPane.showMessageDialog(null, "Digite um valor numerico inteiro");
            jTFNumero1.setText("");
            jTFNumero1.requestFocus();
            return;
        }
        try {
            numero2 = Integer.parseInt(jTFNumero2.getText());
        } catch (NumberFormatException erro) {
            JOptionPane.showMessageDialog(null, "Digite um valor numerico inteiro");
            jTFNumero2.setText("");
            jTFNumero2.requestFocus();
            return;
        }

        doisNumerosObj = new DoisNumerosInteiros(numero1, numero2);
        int resultOperacao = 0;
        switch (op) {
            case '+':
                resultOperacao = doisNumerosObj.adicao();
                break;
            case '-':
                resultOperacao = doisNumerosObj.subtracao();
                break;
            case '*':
                resultOperacao = doisNumerosObj.multiplicacao();
                break;
            case '/':
                resultOperacao = doisNumerosObj.divisao();
                break;
            case '.':
                try {
                    resultOperacao = doisNumerosObj.divisaoPar();
                    break;
                } catch (NaoehPar | ArithmeticException erro4) {
                    JOptionPane.showMessageDialog(this, erro4.getMessage());
                    jTFNumero2.setText("");
                    jTFNumero2.requestFocus();
                    return;
                }
        }//fim do switch
        jLResultado.setText(String.valueOf(doisNumerosObj.getNumero1()) + op + doisNumerosObj.getNumero2() + " = " + String.valueOf(resultOperacao));
    }//fim do método realizaOperacoes

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoisNumerosInteirosAPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoisNumerosInteirosAPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoisNumerosInteirosAPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoisNumerosInteirosAPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoisNumerosInteirosAPP().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBDivPar;
    private javax.swing.JButton jBtAdicao;
    private javax.swing.JButton jBtDiv;
    private javax.swing.JButton jBtLimpar;
    private javax.swing.JButton jBtMultiplicacao;
    private javax.swing.JButton jBtSair;
    private javax.swing.JButton jBtSubtracao;
    private javax.swing.JLabel jLResultado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPOperacoes;
    private javax.swing.JPanel jPResultado;
    private javax.swing.JPanel jPValores;
    private javax.swing.JTextField jTFNumero1;
    private javax.swing.JTextField jTFNumero2;
    // End of variables declaration//GEN-END:variables
}
