/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import Espectador.Espectador;
import Espectador.Pesquisa;
import javax.swing.JOptionPane;

public class Tela extends javax.swing.JFrame {

    private Pesquisa pesquisa;

    public Tela() {
        initComponents();
        setLocationRelativeTo(null);
        pesquisa = new Pesquisa();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDPesquisa = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTIdade = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jRA = new javax.swing.JRadioButton();
        jRB = new javax.swing.JRadioButton();
        jRC = new javax.swing.JRadioButton();
        jRD = new javax.swing.JRadioButton();
        jRE = new javax.swing.JRadioButton();
        jBSalvar = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMOpniao = new javax.swing.JMenu();
        jMIOpiniao = new javax.swing.JMenuItem();
        jMResultado = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jDPesquisa.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Espectador"));

        jLabel1.setText("Idade:");

        jLabel2.setText("Qual sua opinião sobre o filme?");

        buttonGroup1.add(jRA);
        jRA.setText("Ótimo");
        jRA.setActionCommand("A");

        buttonGroup1.add(jRB);
        jRB.setText("Bom");
        jRB.setActionCommand("B");

        buttonGroup1.add(jRC);
        jRC.setText("Regular");
        jRC.setActionCommand("C");

        buttonGroup1.add(jRD);
        jRD.setText("Ruim");
        jRD.setActionCommand("D");

        buttonGroup1.add(jRE);
        jRE.setText("Péssimo");
        jRE.setActionCommand("E");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRD)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRB)
                    .addComponent(jRC)
                    .addComponent(jRD)
                    .addComponent(jRE)
                    .addComponent(jRA))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jBSalvar.setText("Salvar");
        jBSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDPesquisaLayout = new javax.swing.GroupLayout(jDPesquisa.getContentPane());
        jDPesquisa.getContentPane().setLayout(jDPesquisaLayout);
        jDPesquisaLayout.setHorizontalGroup(
            jDPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBSalvar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDPesquisaLayout.setVerticalGroup(
            jDPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBSalvar)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pesquisa de Opinião");

        jMOpniao.setText("Cadastrar");

        jMIOpiniao.setText("Opinião");
        jMIOpiniao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIOpiniaoActionPerformed(evt);
            }
        });
        jMOpniao.add(jMIOpiniao);

        jMenuBar1.add(jMOpniao);

        jMResultado.setText("Listar");

        jMenuItem2.setText("Resultado");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMResultado.add(jMenuItem2);

        jMenuBar1.add(jMResultado);

        jMenu3.setText("Opçoes");

        jMenuItem1.setText("Sair");
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMIOpiniaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIOpiniaoActionPerformed
        jDPesquisa.setSize(400, 300);//janela
        jDPesquisa.setLocationRelativeTo(this);//centro da tela
        jDPesquisa.setModal(true);//nao deixa voltar sem termina 
        jDPesquisa.setVisible(true);//visivel
    }//GEN-LAST:event_jMIOpiniaoActionPerformed

    private void jBSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalvarActionPerformed
        String simNao[] = {"Sim", "Nao"};
        if (jTIdade.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha o campo idade", "Aviso", 0);
            jTIdade.setText("");
            jTIdade.requestFocusInWindow();
            return;
        }
        if (buttonGroup1.getSelection() != null) {
            int salva = JOptionPane.showOptionDialog(this, "Confirma os dados?", "Gravando..", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, simNao, simNao[0]);
            if (salva == 0) {
                Espectador espectador = montaEspectador();
                pesquisa.adiciona(espectador);
            }
            jTIdade.setText(null);
            jTIdade.requestFocusInWindow();
            buttonGroup1.clearSelection();
        } else {
            JOptionPane.showMessageDialog(this, "Dê sua opiniao", "Aviso", 0);
        }

    }//GEN-LAST:event_jBSalvarActionPerformed

    private Espectador montaEspectador() {
        Espectador espectador = new Espectador();
        espectador.setIdade(Integer.parseInt(jTIdade.getText()));
        espectador.setOpiniao(buttonGroup1.getSelection().getActionCommand().charAt(0));
        return espectador;

    }


    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
         JOptionPane.showMessageDialog(this, "Participaram da pesquisa: " + pesquisa.getQtdeRespPesquisa() + "\nResultado: " + pesquisa.dados(pesquisa.ocorrencias()), "Resultado", 1);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBSalvar;
    private javax.swing.JDialog jDPesquisa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMIOpiniao;
    private javax.swing.JMenu jMOpniao;
    private javax.swing.JMenu jMResultado;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRA;
    private javax.swing.JRadioButton jRB;
    private javax.swing.JRadioButton jRC;
    private javax.swing.JRadioButton jRD;
    private javax.swing.JRadioButton jRE;
    private javax.swing.JTextField jTIdade;
    // End of variables declaration//GEN-END:variables
}
